services:
  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: live_config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d live_config']
      interval: 5s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh localhost:27017/live_config --quiet",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
